[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pyservicenow"
authors = [{name = "michaeldcanady"}]
readme = "Readme.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
requires-python = ">3.8.0"

dependencies = [
    "black==22.12.0",
    "bleach==5.0.1",
    "certifi==2022.12.7",
    "cffi==1.15.1",
    "charset-normalizer==2.1.1",
    "click==8.1.3",
    "colorama==0.4.6",
    "commonmark==0.9.1",
    "cryptography==38.0.4",
    "docutils==0.19",
    "idna==3.4",
    "importlib-metadata==6.0.0",
    "jaraco.classes==3.2.3",
    "keyring==23.13.1",
    "more-itertools==9.0.0",
    "mypy-extensions==0.4.3",
    "pathspec==0.10.3",
    "pkginfo==1.9.2",
    "platformdirs==2.6.0",
    "pycparser==2.21",
    "Pygments==2.14.0",
    "pyrestsdk==0.2.7",
    "pyspnego==0.7.0",
    "pywin32-ctypes==0.2.0",
    "readme-renderer==37.3",
    "requests==2.28.1",
    "requests-kerberos==0.14.0",
    "requests-toolbelt==0.10.1",
    "rfc3986==2.0.0",
    "rich==13.0.0",
    "six==1.16.0",
    "StrEnum==0.4.9",
    "tomli==2.0.1",
    "twine==4.0.2",
    "typing_extensions==4.4.0",
    "urllib3==1.26.13",
    "webencodings==0.5.1",
    "zipp==3.11.0"
]

[project.urls]
homepage = "https://github.com/michaeldcanady/pyservicenow#readme"
repository = "https://github.com/michaeldcanady/pyservicenow"

[tool.flit.module]
name = "pyservicenow"

[tool.mypy]
warn_unused_configs = true
files = "pyservicenow"
ignore_missing_imports = true

[tool.yapf]
based_on_style = "pep8"
dedent_closing_brackets = true
each_dict_entry_on_separate_line = true
column_limit = 100

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]